---
rules:
  indent:
    - 2
    - 2
    - {"SwitchCase": 1}
  quotes:
    - 2
    - single
    - avoid-escape
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - "always"
  space-before-function-paren:
    - 2
    - {named: "never", anonymous: "always"}
  space-after-keywords:
    - 2
    - always
  jsx-quotes:
    - 2
    - prefer-double
  brace-style:
    - 2
    - 1tbs
    - {allowSingleLine: true}
  object-curly-spacing:
    - 2
    - never
  curly:
    - 2
  no-fallthrough:
    - 0
  comma-style:
    - 2
    - first
  no-irregular-whitespace:
    - 2
  eqeqeq:
    - 2
    - smart
  no-spaced-func:
    - 2
  array-bracket-spacing:
    - 2
    - never
  key-spacing:
    - 2
    - {beforeColon: false, afterColon: true}
  no-console:
    - 0
  no-unused-vars:
    - 2
    - {args: "none", vars: "all"}
  space-in-parens:
    - 2
    - "never"
  space-unary-ops:
    - 2
    - {words: true, nonwords: false}
  spaced-comment:
    - 2
    - always
    - {exceptions: ["*"]}
  max-depth:
    - 1
    - 4
  radix:
    - 2
    - always
  react/jsx-uses-react:
    - 1
  eol-last:
    - 2
  arrow-body-style:
    - 2
    - as-needed
  arrow-spacing:
    - 2
extends: eslint:recommended
parser: babel-eslint
plugins:
  - react
